blank_issues_enabled: true
contact_links:
  - name: Awesome Aquarium Tech Discussions
    url: https://github.com/ranjithrajv/awesome-aquarium-tech/discussions
    about: Please ask and answer questions here
